name: achtung-die-kurve
region: nyc

# Static site hosting for client (FREE)
static_sites:
  - name: client
    source_dir: /
    build_command: npm install && npm run build
    output_dir: /dist
    index_document: index.html
    error_document: index.html
    routes:
      - path: /
    environment_slug: node-js
    envs:
      - key: NODE_ENV
        value: production
      - key: VITE_WEBSOCKET_URL
        value: "wss://achtung-api.jackstevens.tech"

# WebSocket server (PAID - but only $12/month for basic-xxs)
services:
  - name: websocket-server
    source_dir: /server
    build_command: npm install
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    health_check:
      http_path: /health
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: CORS_ORIGIN
        value: "https://achtung.jackstevens.tech"
