name: achtung-die-kurve
region: nyc

services:
  # WebSocket Server
  - name: websocket-server
    source_dir: /
    dockerfile_path: server/Dockerfile
    github:
      branch: main
      deploy_on_push: true
    health_check:
      http_path: /health
      success_codes:
        - 200
    http_port: 3001
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /socket.io
    environment_slug: node-js
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: CORS_ORIGIN
        value: "https://achtung.jackstevens.tech"

  # Static Site (Client) - Docker build only
  - name: client
    dockerfile_path: Dockerfile
    github:
      branch: main
      deploy_on_push: true
    health_check:
      http_path: /health
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: VITE_WEBSOCKET_URL
        value: "wss://achtung.jackstevens.tech"
