name: achtung-die-kurve
region: nyc

services:
  # Static Site (Client) - serves main application
  - name: client
    source_dir: /
    build_command: npm install && npm run build
    run_command: npm run preview -- --host 0.0.0.0 --port $PORT
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: VITE_WEBSOCKET_URL
        value: "wss://${websocket-server.PUBLIC_URL}"

  # WebSocket Server - serves API and WebSocket connections
  - name: websocket-server
    source_dir: /server
    build_command: npm install
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    health_check:
      http_path: /health
    routes:
      - path: /socket.io
      - path: /api
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: CORS_ORIGIN
        value: "${client.PUBLIC_URL}"
