name: achtung-die-kurve
region: syd

# Combined server that serves both static files and WebSocket
services:
  - name: app-server
    github:
      repo: oilytortoise/achtung-die-kurve
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: npm ci && npm run build && cd server && npm install
    run_command: cd server && npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    routes:
      - path: /
    health_check:
      http_path: /health
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: VITE_WEBSOCKET_URL
        value: "wss://achtung-die-kurve-o4449.ondigitalocean.app"
      - key: CORS_ORIGIN
        value: "https://achtung-die-kurve-o4449.ondigitalocean.app"
